<?xml version="1.0"?>
<robot name="sam_bot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Define robot constants -->
  <xacro:property name="base_width" value="0.42"/>
  <xacro:property name="base_length" value="0.42"/>
  <xacro:property name="base_height" value="0.42"/>

  <xacro:property name="eyes_width" value="0.15"/>
  <xacro:property name="eyes_length" value="0.42"/>
  <xacro:property name="eyes_height" value="0.15"/>

  <xacro:property name="neck_width" value="0.1"/>
  <xacro:property name="neck_length" value="0.1"/>
  <xacro:property name="neck_height" value="0.4"/>
  

  <xacro:property name="wheel_radius" value="0.10"/>
  <xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="wheel_ygap" value="0.025"/>
  <xacro:property name="wheel_zoff" value="0.18"/>
  <xacro:property name="wheel_xoff" value="0.12"/>

  <xacro:property name="caster_xoff" value="0.14"/>

  <!-- Define inertial property macros -->
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (3*r*r + h*h)}" iyz="0.0" izz="${(m/2) * r*r}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${(2/5) * m * r*r}" ixy="0.0" ixz="0.0" iyy="${(2/5) * m * r*r}" iyz="0.0" izz="${(2/5) * m * r*r}"/>
    </inertial>
  </xacro:macro>

  <!-- Robot Footprint -->
  <link name="base_footprint">
    <inertial>
      <mass value="0.001"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <!-- Robot Base -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="15" w="${base_width}" h="${base_height}" d="${base_length}"/>
  </link>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 ${(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
  </joint>


  <!-- Robot Neck -->
  <link name="neck_link">
    <visual>
      <geometry>
        <box size="${neck_length} ${neck_width} ${neck_height}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>
    <xacro:box_inertia m="15" w="${neck_width}" h="${neck_height}" d="${neck_length}"/>
  </link>

  <!-- Robot Eyes Left -->
  <link name="eyes_left_link">
    <visual>
      <geometry>
        <box size="${eyes_length} ${eyes_width} ${eyes_height}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>
    <xacro:box_inertia m="15" w="${eyes_width}" h="${eyes_height}" d="${eyes_length}"/>
  </link>


    <!-- Robot Eyes Right -->
  <link name="eyes_right_link">
    <visual>
      <geometry>
        <box size="${eyes_length} ${eyes_width} ${eyes_height}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>
    <xacro:box_inertia m="15" w="${eyes_width}" h="${eyes_height}" d="${eyes_length}"/>
  </link>


  <!-- neck Footprint -->
   <joint name="neck_joint" type="fixed">
    <parent link="base_link"/>
    <child link="neck_link"/>
    <origin xyz="0.0 0.0 ${base_width-0.1}" rpy="0 0 0"/>
  </joint>

  <!-- Eyes Right Footprint -->
   <joint name="eyes_left_joint" type="fixed">
    <parent link="neck_link"/>
    <child link="eyes_left_link"/>
    <origin xyz="0.0 -0.13 0.1" rpy="0 0 0"/>
  </joint>

  <!-- Eyes Right Footprint -->
   <joint name="eyes_right_joint" type="fixed">
    <parent link="neck_link"/>
    <child link="eyes_right_link"/>
    <origin xyz="0.0 0.13 0.1" rpy="0 0 0"/>
  </joint>

  <!-- Wheels -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>
    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="drivewhl_l" x_reflect="-1" y_reflect="1"/>
  <xacro:wheel prefix="drivewhl_r" x_reflect="-1" y_reflect="-1"/>

  <!-- Caster Wheel -->
  <link name="front_caster">
    <visual>
      <geometry>
        <sphere radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
      </geometry>
    </collision>
    <xacro:sphere_inertia m="0.5" r="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
  </link>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_caster"/>
    <origin xyz="${caster_xoff} 0.0 ${-(base_height/2)}" rpy="0 0 0"/>
  </joint>




<!-- ZRACHKI -->

 <!-- Robot ZRACHKI Eyes Left -->
  <link name="zrachki_eyes_left_link">
    <visual>
      <geometry>
        <box size="${eyes_length} ${eyes_width/2} ${eyes_height/2}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 0.0 0.0 0.0"/>
      </material>
    </visual>
    <xacro:box_inertia m="15" w="${eyes_width/2}" h="${eyes_height/2}" d="${eyes_length}"/>
  </link>


    <!-- Robot ZRACHKI Eyes Right -->
  <link name="zrachki_eyes_right_link">
    <visual>
      <geometry>
        <box size="${eyes_length} ${eyes_width/2} ${eyes_height/2}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 0.0 0.0 0.0"/>
      </material>
    </visual>
    <xacro:box_inertia m="15" w="${eyes_width/2}" h="${eyes_height/2}" d="${eyes_length}"/>
  </link>


    <!-- EZRACHKI yes Right Footprint -->
   <joint name="zrachki_eyes_left_joint" type="fixed">
    <parent link="eyes_left_link"/>
    <child link="zrachki_eyes_left_link"/>
    <origin xyz="-0.01 0.0 0.0" rpy="0 0 0"/>
  </joint>

  <!-- ZRACHKI Eyes Right Footprint -->
   <joint name="zrachki_eyes_right_joint" type="fixed">
    <parent link="eyes_right_link"/>
    <child link="zrachki_eyes_right_link"/>
    <origin xyz="-0.01 0.0 0.0" rpy="0 0 0"/>
  </joint>





</robot>